title: WonJae Lee
logo: /assets/img/profile.JPG
#description: text below image
#show_downloads: true
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
